[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2==3.1.4",
    "markupsafe==3.0.1",
    "meltdown==0.0.4",
    "toml==0.10.2",
    "watchdog==5.0.3",
]
