# A basic action that automatically delivers blog updates to the production server.

name: CI

on: [push]

jobs:
  test:
    runs-on: Ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Linting
        run: uv tool run ruff check

      - name: Formatting
        run: uv tool run ruff format --check

  deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: Ubuntu-24.04
    steps:
      - name: deploy on production server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd blog
            git fetch --all
            git reset --hard origin/main
            /home/blog/.local/bin/uv run blog.py build --clean --out /home/blog/html
